# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e71ba593c96713ceea6064ebf53ae2c2e426629c17e249660753d9dbaed8c997e349eb4f9ef813f338f7e071f99d11a3fe37c05fe526fbdcf43829a752129055

test:
  secret_key_base: e56f609d9f62e1bb9aa55ac7afcdd6ce621c4889d96dadb0fcad1508b5600d421017ddd286528da88da2d3c7da243d4bd4379247b8be53fab837000150813ed2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


  